### ISSUE TITLE
Logs are not stored in Database using Spring JPA

### ISSUE THREAD

**Issue by nurrony** [esanchezros/quickfixj-spring-boot-starter#134]
I am using Postgres with Spring Boot 3.2.4 along with Spring Data JPA and configured `MessageStoreFactory` and `LogFactory` as follows

```java

@Configuration
public class MyFixClientConfig {

    @Bean
    public Application clientApplication(final SessionSettings sessionSettings) {
        return new MyQuickfixApplication(sessionSettings);
    }

    @Bean
    public Initiator clientInitiator(Application clientApplication,
            MessageStoreFactory clientMessageStoreFactory,
            SessionSettings clientSessionSettings, 
            LogFactory clientLogFactory,
            MessageFactory clientMessageFactory) throws ConfigError {

        return new ThreadedSocketInitiator(clientApplication, clientMessageStoreFactory, clientSessionSettings, clientLogFactory, clientMessageFactory);
    }

    @Bean
    public MessageStoreFactory clientMessageStoreFactory(SessionSettings clientSessionSettings, DataSource dataSource) {
        JdbcStoreFactory jdbcStoreFactory = new JdbcStoreFactory(clientSessionSettings);
        jdbcStoreFactory.setDataSource(dataSource);
        return jdbcStoreFactory;
    }

    @Bean
    public LogFactory clientLogFactory(SessionSettings clientSessionSettings, DataSource dataSource) {
        JdbcLogFactory jdbcLogFactory = new JdbcLogFactory(clientSessionSettings);
        jdbcLogFactory.setDataSource(dataSource);
        return jdbcLogFactory;
    }
}

```
**My Quicfix/J config**
```
JdbcLogHeartBeats=N
UseJDBCLogger=Y
JdbcUser=postgres
JdbcPassword=****
JdbcDriver=org.postgresql.Driver
JdbcURL=jdbc:postgresql://localhost/oms_orders?currentSchema=client
JdbcLogEventTable=fix_event_log
JdbcSessionIdDefaultPropertyValue=NULL
JdbcStoreMessagesTableName=fix_messages
JdbcStoreSessionsTableName=fix_sessions
JdbcLogIncomingTable=fix_messages_log_incoming
JdbcLogOutgoingTable=fix_messages_log_outgoing
```
In `application.yaml` I use these settings
```yml
spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost/oms_orders?currentSchema=client
    driver-class-name: org.postgresql.Driver

# QuickfixJ settings
quickfixj:
  client:
    enabled: true
    jmx-enabled: true
    config: ${QUIICKFIXJ_CLIENT_CONFIG_FILE:classpath:quickfixj-client.cfg}
    message-store-factory: jdbc
    log-factory: jdbc
```
What I am doing wrong? Please help me. Thanks in advance
