### ISSUE TITLE
use @EnableQuickFixJClient  HTTP interface unreachable

### ISSUE THREAD

**Issue by maolinHu** [esanchezros/quickfixj-spring-boot-starter#86]
SpringBoot with QuickFIX/J Client, After the Application is started, all web interfaces cannot be accessed, include http://localhost:8080/actuator/quickfixjclient

**Comment by esanchezros** [comment]
Hi @maolinHu 

Could you try adding this to your application.yml:

```
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    quickfixjclient:
      enabled: true
```
